### ISSUE TITLE
Add cilium egress gateway management

### ISSUE THREAD

**Issue by bryopsida** [bryopsida/infra#28]
As a maintainer I want to be able to control where traffic egresses from the cluster to the `world`. One way to do this is through a cilium egress gateway.  To that end I must be able to do the following.

1) Enable the egress gateway feature in cilium in inventory
2) manage cilium egress gateway policies in inventory
3) management of egress gateway policies must be able to set the adapter device to use

Enablement of egress gateway docs can be found at: https://docs.cilium.io/en/stable/network/egress-gateway/

Configuration to scope to dev can be done in policy like so.

``` yaml
egressGateway:
  nodeSelector:
    matchLabels:
      testLabel: testVal
  interface: ethX
```
